import type { Opportunity, Company, Student, StudentSkill, Course, Career, SkillDemand, Placement, Certificate, TaskWorkspace, Application } from './engine';
import type { FeedJob } from '../context/AppContext';

export const demoCompanies: Company[] = [
  { id: 1, name: 'Patanjali', sector: 'Ayurveda & Wellness', location: 'Haridwar', size_text: '5000+', rating: 4.5, color: '#0d7a5f', about: 'Wellness products and herbal care.', verified: true },
  { id: 2, name: 'Himalaya', sector: 'Nutrition & Health', location: 'Bengaluru', size_text: '2000+', rating: 4.4, color: '#2563eb', about: 'Herbal nutrition and everyday wellness.', verified: true },
  { id: 3, name: 'Kapiva', sector: 'Functional Nutrition', location: 'Mumbai', size_text: '500+', rating: 4.6, color: '#7c3aed', about: 'Ayurveda-based functional nutrition.', verified: true },
  { id: 4, name: 'NirogStreet', sector: 'Digital Health', location: 'Noida', size_text: '300+', rating: 4.3, color: '#e8930c', about: 'Telehealth and preventive care platform.', verified: true },
  { id: 5, name: 'Dabur', sector: 'Consumer Wellness', location: 'Ghaziabad', size_text: '10000+', rating: 4.7, color: '#0e7490', about: 'Home & personal wellness products.', verified: true },
];

export const demoStudents: Student[] = [
  {
    id: 1,
    name: 'Aarav Sharma',
    email: 'aarav@example.com',
    college: 'National Institute of Ayurveda',
    degree: 'BAMS',
    year: 'Final Year',
    location: 'Nagpur',
    headline: 'Ayurveda + digital health student',
    avatar_color: '#0d7a5f',
    readiness_score: 82,
    xp: 420,
    streak_days: 18,
    level_text: 'Career Ready',
    resume_text: 'Python, SQL, Ayurveda wellness, content strategy, digital marketing.',
    portfolio_url: 'https://example.com/aarav',
  },
];

export const demoSkills: StudentSkill[] = [
  { id: 1, student_id: 1, skill_name: 'Python', category: 'Digital', level: 3, proficiency_pct: 80, verified: true, source: 'Portfolio' },
  { id: 2, student_id: 1, skill_name: 'SQL', category: 'Data', level: 3, proficiency_pct: 75, verified: true, source: 'Project' },
  { id: 3, student_id: 1, skill_name: 'Ayurvedic Diagnosis', category: 'Clinical', level: 4, proficiency_pct: 90, verified: true, source: 'College' },
  { id: 4, student_id: 1, skill_name: 'Digital Marketing', category: 'Marketing', level: 2, proficiency_pct: 60, verified: false, source: 'Self-taught' },
];

export const demoOpportunities: Opportunity[] = [
  {
    id: 101,
    title: 'Ayurveda Wellness Content Intern',
    company_id: 1,
    type: 'internship',
    domain: 'Ayurveda & Wellness',
    location: 'Haridwar',
    remote: false,
    stipend: '₹12,000/month',
    stipend_num: 12000,
    duration: '8 weeks',
    urgency: 'soon',
    starts_in: 'This month',
    skills_required: ['Ayurvedic Diagnosis', 'Content Writing', 'Digital Marketing'],
    description: 'Create educational content and help with wellness campaigns.',
    openings: 4,
    applicants_count: 18,
    status: 'open',
    posted_at: 'Today',
    deadline: '2 weeks',
    color: '#0d7a5f',
  },
  {
    id: 102,
    title: 'Product Research Micro-Internship',
    company_id: 2,
    type: 'micro-internship',
    domain: 'Research & Product',
    location: 'Bengaluru',
    remote: true,
    stipend: '₹8,000/project',
    stipend_num: 8000,
    duration: '2 weeks',
    urgency: 'instant',
    starts_in: 'Starts today',
    skills_required: ['Python', 'Research Writing', 'SQL'],
    description: 'Analyze wellness product data and summarize insights for launch planning.',
    openings: 3,
    applicants_count: 11,
    status: 'open',
    posted_at: 'Today',
    deadline: '3 days',
    color: '#2563eb',
  },
  {
    id: 103,
    title: 'Same-Day Task: Landing Page Build',
    company_id: 3,
    type: 'same-day-task',
    domain: 'Digital Experience',
    location: 'Remote',
    remote: true,
    stipend: '₹4,000 flat',
    stipend_num: 4000,
    duration: '1 day',
    urgency: 'instant',
    starts_in: 'Today',
    skills_required: ['React', 'Frontend Development', 'UI Design'],
    description: 'Build a quick conversion-focused landing page for a wellness product demo.',
    openings: 2,
    applicants_count: 29,
    status: 'open',
    posted_at: 'Today',
    deadline: 'Same day',
    color: '#e8930c',
  },
  {
    id: 104,
    title: 'Clinical Documentation Analyst',
    company_id: 4,
    type: 'part-time',
    domain: 'Healthcare Ops',
    location: 'Noida',
    remote: false,
    stipend: '₹18,000/month',
    stipend_num: 18000,
    duration: '6 months',
    urgency: 'soon',
    starts_in: '2 weeks',
    skills_required: ['Clinical Documentation', 'Patient Counselling', 'SQL'],
    description: 'Maintain patient documentation and support clinical workflows.',
    openings: 5,
    applicants_count: 24,
    status: 'open',
    posted_at: '2 days ago',
    deadline: '10 days',
    color: '#7c3aed',
  },
  {
    id: 105,
    title: 'Brand Marketing Intern',
    company_id: 5,
    type: 'internship',
    domain: 'Marketing',
    location: 'Ghaziabad',
    remote: false,
    stipend: '₹15,000/month',
    stipend_num: 15000,
    duration: '10 weeks',
    urgency: 'flexible',
    starts_in: 'Next month',
    skills_required: ['Digital Marketing', 'Public Speaking', 'Content Writing'],
    description: 'Support omnichannel planning and creator engagement for consumer wellness campaigns.',
    openings: 7,
    applicants_count: 32,
    status: 'open',
    posted_at: '1 day ago',
    deadline: '3 weeks',
    color: '#0e7490',
  },
  {
    id: 106,
    title: 'Wellness App UX Challenge',
    company_id: 2,
    type: 'challenge',
    domain: 'Product Design',
    location: 'Remote',
    remote: true,
    stipend: '₹10,000 prize',
    stipend_num: 10000,
    duration: '1 week',
    urgency: 'soon',
    starts_in: 'This week',
    skills_required: ['UI Design', 'Figma', 'User Research'],
    description: 'Create a user-friendly prototype for a health-tracking and wellness coach dashboard.',
    openings: 8,
    applicants_count: 41,
    status: 'open',
    posted_at: 'Today',
    deadline: '4 days',
    color: '#dc2626',
  },
];

export const demoFeed: FeedJob[] = [
  {
    id: 'ex-1',
    internal_id: null,
    title: 'AI Wellness Operations Associate',
    company_name: 'NirogStreet',
    company_id: 4,
    location: 'Remote',
    remote: true,
    type: 'part-time',
    domain: 'Digital Health',
    stipend: '₹20,000/month',
    salary_text: '₹20,000/month',
    source: 'LinkedIn',
    source_url: 'https://www.linkedin.com/jobs',
    external_id: 'li-1',
    skills: ['SQL', 'Python', 'Patient Counselling'],
    skills_required: ['SQL', 'Python', 'Patient Counselling'],
    summary: 'Support workflow automation and patient communication for digital health operations.',
    description: 'Support workflow automation and patient communication for digital health operations.',
    posted_text: 'Today',
    posted_at: new Date().toISOString(),
    urgency: 'soon',
    starts_in: 'Remote start',
    duration: 'Part-time',
    openings: 2,
    applicants_count: 16,
    status: 'open',
    color: '#0d7a5f',
    verified: true,
    external: true,
  },
  {
    id: 'ex-2',
    internal_id: null,
    title: 'Digital Marketing Intern',
    company_name: 'Kapiva',
    company_id: 3,
    location: 'Mumbai',
    remote: false,
    type: 'internship',
    domain: 'Marketing',
    stipend: '₹12,500/month',
    salary_text: '₹12,500/month',
    source: 'Naukri',
    source_url: 'https://www.naukri.com/',
    external_id: 'nk-2',
    skills: ['Digital Marketing', 'Content Writing', 'Public Speaking'],
    skills_required: ['Digital Marketing', 'Content Writing', 'Public Speaking'],
    summary: 'Support content and campaign planning for the Kapiva brand.',
    description: 'Support content and campaign planning for the Kapiva brand.',
    posted_text: '1 day ago',
    posted_at: new Date().toISOString(),
    urgency: 'flexible',
    starts_in: 'Next month',
    duration: '8 weeks',
    openings: 3,
    applicants_count: 12,
    status: 'open',
    color: '#7c3aed',
    verified: true,
    external: true,
  },
];

export const demoCourses: Course[] = [
  { id: 1, title: 'Python for Health Data', provider: 'SkillSetu Academy', duration: '4 weeks', level_text: 'Beginner', rating: 4.8, learners: 1200, skills_covered: ['Python', 'SQL'], url: '#', free: true },
  { id: 2, title: 'Digital Marketing Bootcamp', provider: 'SkillSetu Academy', duration: '3 weeks', level_text: 'Intermediate', rating: 4.7, learners: 980, skills_covered: ['Digital Marketing'], url: '#', free: true },
];

export const demoCareers: Career[] = [
  { id: 1, title: 'Digital Wellness Analyst', domain: 'Digital Health', description: 'Blend data + customer care + wellness workflow design.', required_skills: [{ skill: 'Python', level: 3, weight: 20 }, { skill: 'SQL', level: 3, weight: 20 }, { skill: 'Patient Counselling', level: 2, weight: 15 }], avg_stipend: '₹18k–₹30k', demand_index: 92, growth: '+28%', color: '#0d7a5f' },
];

export const demoSkillDemand: SkillDemand[] = [
  { id: 1, skill_name: 'Python', category: 'Digital', demand_score: 92, growth_pct: 30, avg_stipend_boost: '+₹8k', openings: 22 },
  { id: 2, skill_name: 'SQL', category: 'Data', demand_score: 88, growth_pct: 25, avg_stipend_boost: '+₹6k', openings: 18 },
  { id: 3, skill_name: 'Digital Marketing', category: 'Marketing', demand_score: 81, growth_pct: 18, avg_stipend_boost: '+₹5k', openings: 15 },
];

export const demoPlacements: Placement[] = [
  { id: 1, student_name: 'Aarav Sharma', college: 'National Institute of Ayurveda', company_name: 'Kapiva', role_title: 'Content Analyst', package_text: '₹8.5 LPA', year: 2025, via: 'SkillSetu' },
];

export const demoApplications: Application[] = [];
export const demoCertificates: Certificate[] = [];
export const demoWorkspaces: TaskWorkspace[] = [];
